### ISSUE TITLE
The Ground terminal will abort the connection forever when ATS sends the incorrect data. 

### ISSUE THREAD

**Issue by JaeWJ** [jacnel2/GroundTerminalSystem#5]
At the end of the day, a data stream requires both the client and server to be in constant communication with each other.  If one were to be interrupted, you'd want to close the stream because you don't know if A, the client just decided to leave or B, the client didn't want to leave but had an issue. Leaving streams and ports open is a bad idea

**Comment by jacnel2** [comment]
Yes, while it may appear that this is a bug, if the ATS client terminates the connection for whatever reason the server is designed to immediately close the connection on its side. This is so that open ports, and streams aren't left around. The reason being that while you could set up a system where the stream stays open if there's no final message sent to close the stream, the server has no idea if the client will actually re-join the stream and as such, could lead to connections remaining open.

If a client terminates itself before sending all the data it can instead open a new connection/stream and the ground terminal will handle it. I've designed the software so that data from flights are combined into a single Flight instance for the specific tail. No matter who sends the data or when the data is sent.
